CREATE TABLE customer_support_tickets (
    ticket_id             bigserial PRIMARY KEY,
    subject               text,
    body                  text,
    answer                text,
    type                  varchar(50),
    queue                 varchar(50),
    priority              varchar(20),
    language              varchar(10),
    tags                  jsonb,

    -- Fields Generated by the IA inference
    predicted_category    varchar(50),
    confidence            float,
    summary               text,
    processed_at          timestamp,

    -- Field derivative for business logic
    ground_truth_category varchar(50)   -- map -> queue -> category
);

-- Optimized indexes
CREATE INDEX idx_queue ON customer_support_tickets (queue);
CREATE INDEX idx_priority ON customer_support_tickets (priority);
CREATE INDEX idx_predicted_category ON customer_support_tickets (predicted_category);
CREATE INDEX idx_ground_truth ON customer_support_tickets (ground_truth_category);
CREATE INDEX idx_processed_at ON customer_support_tickets (processed_at);
